"""posts table

Revision ID: 787aa3e42501
Revises: 744e25d652d6
Create Date: 2018-12-21 23:08:12.898796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787aa3e42501'
down_revision = '744e25d652d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_usernme', table_name='user')
    op.drop_column('user', 'usernme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernme', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_usernme', 'user', ['usernme'], unique=1)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
